### ISSUE TITLE
rename container to `gsa_mixer.sif`?

### ISSUE THREAD

**Issue by espenhgn** [precimed/gsa-mixer#1]
Minor thing perhaps, but since there is another `mixer.sif` it'd be good to avoid namespace confusion until these projects are merged. Also, the same docker target (`docker build -t mixer ....`) is used both here and in comorment/mixer which may be a concern.

**Comment by ofrei** [comment]
Good point, I'll rename

**Comment by espenhgn** [comment]
no longer relevant, closing.
