### ISSUE TITLE
Discrepancies between GSA_MIXER.job and main page README

### ISSUE THREAD

**Issue by nievergeltlab** [precimed/gsa-mixer#6]
Hi,

On the readme page of this github, there are some example commands for running gsa-mixer

For --gsa-base, the input parameters include:
--go-file go-file-baseline.csv \
--go-file-test go-file-geneset.csv 

For --gsa-full the input parameters include:
--go-file go-file-gene.csv \
--go-file-test go-file-geneset.csv 

But is --go-file-test compatible with --gsa-base? I thought that you need to specify --load-params-file to use --go-file-test. The input json file for this parameter is an output of --gsa-base, thus would not be available for the base step. 

In contrast to the README page, the file GSA_MIXER.job in the scripts directory does not have '--go-file-test' as a parameter when executing --gsa-base

Also in contrast to the README page, the file GSA_MIXER.job does not include the --extract command that is used to extract subsets of reference SNPs, nor does it include the array indexing of the multiple runs.

thanks!

**Comment by humanpaingeneticslab** [comment]
Greetings!

It seems that we're in the same trying-to-get-this-thing-work boat! :-)

Regarding the issue above, I was able to run the tutorial by removing this line:
--go-file-test go-file-geneset.csv
when calling '${MIXER_PY} plsa --gsa-base ...'

Now, I was wondering if you could get your hands on either UKB's or HRC's reference files, those listed in that section here:
https://github.com/precimed/gsa-mixer?tab=readme-ov-file#download-ld-reference-files

Thanks!

**Comment by ofrei** [comment]
@nievergeltlab @humanpaingeneticslab hi, and thanks for asking - very good questions. Sorry for my very delayed response. I've updates the README file to resolve these issues you've mentioned here.

1) Removing ``--go-file-test go-file-geneset.csv`` when calling ``--gsa-base`` is a correct thing to do. ``--gsa-base`` should only use ``--go-file``, but not ``--go-file-test``. You're right that ``--go-file-test`` is NOT compatible with --gsa-base. The idea is that ``--go-file-test`` will trigger the computation of fold enrichments, i.e. heritability ratios between "full" and "baseline" models. For this to work ``--gsa-full`` require ``--load-params-file``.  The README.md is now in sync with ``scripts/GSA_MIXER.job``, and both of them do not have ``--go-file-test``  for the ``--gsa-base`` step.

2) ``GSA_MIXER.job does not include the --extract command`` - yes, this is correct, and 20 re-runs are no longer necessary for the GSA-MiXeR.  README.md file is now updated accordingly. The procedure with 20 re-runs  was used for the results in the [medrxiv](https://www.medrxiv.org/content/10.1101/2022.12.08.22283159v1) version of the manuscript, but as part of the revisions it was replased with hessian-based error bars on parameter estimates, thus re-runs were no longer necessary for GSA-MiXeR. As a side note: the cross-trait mixer still relies on 20 re-runs; hopefully this won't be two confusing as for the old cross-trait MiXeR lives as its  own software project, hosted in [this](https://github.com/precimed/mixer) and [this](https://github.com/comorment/mixer) repos. I'm hoping to  consolidate this together at some point later on.

3) RE downloading of the UKB's or HRC's reference files. Unfortunately sharing full LD matrices as they were used was not possible (see details below). For now I provided links to previous 1kG EUR reference panel, used for cross-trait MiXeR analysis, and augumented it with reference files needed for ``--annot-file`` argument (same annotations as used in cross-trait MiXeR). With new 1kG reference dataset it's probably a good idea to update this reference panel to include all 1kG subjects - and this might be as good as using HRC-derived reference panel. I opened #14 to track this.

RE possibility of sharing UKB- and HRC- derived LD matrices: for the HRC I received a few suggestions from HRC data access committee. Most viable suggestion was to split the genome in block of ca. 10 megabase each, and share LD matrix within each block, without sharing LD correlations among blocks. This would  avoid the risk of re-constructing genomes of individual participants - with only potential risk of reconstructing 10 MB-large blocks. This however may break through the boundaries of individual genes, and we would need to do further validation if this approach works well. For UKB, I haven't received any response despite reminders. Sharing LD matrix without their explicit permission is really not an option, I'd rather improve the instructions on how to derive the MiXeR reference panel  from UKB raw files.  Some notes are [here](https://github.com/precimed/gsa-mixer/blob/main/reference/ukb_EUR_qc/about_UKB_qc.txt) for UKB and [here](https://github.com/precimed/gsa-mixer/blob/main/reference/hrc_EUR_qc/about_HRC_qc.txt) for HRC. Let me know if you're trying to reproduce this and need further input!

**Comment by ofrei** [comment]
Closing this for now, but please reopen if this hasn't been addressed!
